version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
file_exist_behavior: OVERWRITE
permissions:
    - object: /
      pattern: "**"
      owner: root
      group: root
hooks:
    AfterInstall:
        - location: backend-deploy-start.sh
          timeout: 300
          runas: root