server:
  port: 7020

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: ${DB_PLATFORM}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}