server:
  port: 7070

spring:
  application:
    name: profile-service
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: ${DB_PLATFORM}

cloud:
  aws:
    s3:
      profile-bucket: ${BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URL}