apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  JWT_SECRET_KEY:
  JWT_EXP_TIME_MS:
  BUCKET:
  AWS_S3_ACCESS_KEY:
  AWS_S3_SECRET_KEY:
  REGION:
  USERNAME:
  PASSWORD:
  DB_URL:
  DB_DRIVER: