
jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: ${JWT_EXP_TIME_MS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

cloud:
  aws:
    s3:
      profile-bucket: ${BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false