jwt:
  secret-key: abcdefghijklmnopqrstuvwxyz0123456789
  token:
    expired-time-ms: 30000000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.10.101/test
    username: latest
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true