name: Frontend CI/CD

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]
env:
  S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Install Dependencies
      run: |
        cd ./frontend
        npm i --force
    - name: Project Test
      run: |
        cd ./frontend
        npm run test
    - name: Project Build
      run: |
        cd ./frontend
        npm run build
    - name: Configuration AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Upload to S3
      run: | 
        cd ./frontend
        aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }}
        
    - name: Test Report
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./frontend/test-results/*.xml
